name: Mac M1 SSH Session
on:
  push:
    branches:
      - test_mac

jobs:
  build:
    runs-on: macos-14 # CRITICAL: macos-14 is Apple Silicon (M1). macos-13 is Intel.
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: brew install gcc cmake

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
